// Lecciones educativas sobre Inteligencia Artificial
export const lessonsData = [
    {
        id: '1',
        title: '¿Qué es la IA?',
        subtitle: 'Fundamentos básicos',
        description: 'Descubre qué es realmente la Inteligencia Artificial y cómo funciona. Aprende los conceptos fundamentales que te permitirán comprenderla como una herramienta poderosa.',
        icon: '🤖',
        duration: '10 min',
        level: 'Principiante',
        progress: 0,
        color: '#193CB8',
        topics: ['Definición de IA', 'Machine Learning', 'Redes Neuronales', 'Aplicaciones cotidianas'],
    },
    {
        id: '2',
        title: 'IA Creativa',
        subtitle: 'Potencia tu imaginación',
        description: 'Aprende a usar la IA como aliado creativo. Genera ideas, diseña contenido y explora nuevas posibilidades que amplíen tu capacidad creativa.',
        icon: '🎨',
        duration: '15 min',
        level: 'Principiante',
        progress: 0,
        color: '#6E11B0',
        topics: ['Generación de ideas', 'Brainstorming con IA', 'Creación de contenido', 'Diseño asistido'],
    },
    {
        id: '3',
        title: 'Investigación Inteligente',
        subtitle: 'Busca y analiza mejor',
        description: 'Descubre cómo usar la IA para investigar de manera más eficiente, analizar información compleja y encontrar respuestas precisas.',
        icon: '🔍',
        duration: '12 min',
        level: 'Intermedio',
        progress: 0,
        color: '#42D3F2',
        topics: ['Búsqueda avanzada', 'Análisis de datos', 'Síntesis de información', 'Verificación de fuentes'],
    },
    {
        id: '4',
        title: 'Resolución de Problemas',
        subtitle: 'Piensa estratégicamente',
        description: 'Utiliza la IA para analizar problemas complejos, generar soluciones innovadoras y tomar decisiones más informadas.',
        icon: '💡',
        duration: '18 min',
        level: 'Intermedio',
        progress: 0,
        color: '#4D179A',
        topics: ['Análisis de problemas', 'Generación de soluciones', 'Toma de decisiones', 'Optimización'],
    },
    {
        id: '5',
        title: 'IA en el Trabajo',
        subtitle: 'Productividad profesional',
        description: 'Integra la IA en tu flujo de trabajo para aumentar tu eficiencia, automatizar tareas repetitivas y enfocarte en lo importante.',
        icon: '💼',
        duration: '20 min',
        level: 'Intermedio',
        progress: 0,
        color: '#372AAC',
        topics: ['Automatización', 'Gestión de tiempo', 'Herramientas profesionales', 'Workflows inteligentes'],
    },
    {
        id: '6',
        title: 'IA en Educación',
        subtitle: 'Aprende mejor',
        description: 'Descubre cómo la IA puede transformar tu experiencia de aprendizaje, personalizar tu educación y mejorar tu rendimiento académico.',
        icon: '📚',
        duration: '14 min',
        level: 'Principiante',
        progress: 0,
        color: '#46ECD5',
        topics: ['Aprendizaje personalizado', 'Tutores virtuales', 'Recursos educativos', 'Evaluación adaptativa'],
    },
    {
        id: '7',
        title: 'Ética y IA',
        subtitle: 'Uso responsable',
        description: 'Desarrolla una mentalidad crítica sobre el uso responsable de la IA. Aprende sobre privacidad, sesgos y consideraciones éticas.',
        icon: '⚖️',
        duration: '16 min',
        level: 'Avanzado',
        progress: 0,
        color: '#615FFF',
        topics: ['Privacidad de datos', 'Sesgos algorítmicos', 'Transparencia', 'Responsabilidad social'],
    },
    {
        id: '8',
        title: 'Prompts Efectivos',
        subtitle: 'Comunícate con IA',
        description: 'Domina el arte de escribir prompts efectivos para obtener los mejores resultados de las herramientas de IA.',
        icon: '✍️',
        duration: '15 min',
        level: 'Intermedio',
        progress: 0,
        color: '#53EAFD',
        topics: ['Estructura de prompts', 'Contexto y claridad', 'Iteración', 'Mejores prácticas'],
    },
];

// Información del usuario para el perfil
export const userProfile = {
    name: 'Estudiante IA',
    email: 'estudiante@ia.com',
    level: 'Principiante',
    lessonsCompleted: 0,
    totalLessons: lessonsData.length,
    streakDays: 0,
    joinDate: 'Marzo 2026',
    achievements: [
        { id: '1', title: 'Primera lección', icon: '🎯', unlocked: false },
        { id: '2', title: 'Semana completa', icon: '🔥', unlocked: false },
        { id: '3', title: 'Nivel intermedio', icon: '⭐', unlocked: false },
        { id: '4', title: 'Maestro IA', icon: '👑', unlocked: false },
    ],
};
