export const lessonsData = [
    {
        id: 1,
        title: "Ingresa a la aplicación",
        subtitle: "Paso inicial del curso",
        icon: "login",
        duration: "5 min",
        level: "Móvil / Digital",
        color: "#193CB8",
        stepType: "entry",
        description:
            "El estudiante abre la app desde el celular o computador para comenzar el módulo sin depender de equipos de alta gama.",
        topics: [
            "Acceso desde celular o computador",
            "Interfaz responsiva",
            "No requiere equipo potente",
            "Inicio rápido del recorrido",
        ],
    },
    {
        id: 2,
        title: "Descarga el manual PDF",
        subtitle: "Guía liviana de uso",
        icon: "picture-as-pdf",
        duration: "7 min",
        level: "Económico + Simple",
        color: "#D32F2F",
        stepType: "manual",
        description:
            "Descarga un manual liviano con la guía de uso del curso y el material base de la unidad 1.",
        topics: [
            "Archivo PDF liviano",
            "Guía de introducción a la IA",
            "Descarga gratuita",
            "Material para revisar sin conexión",
        ],
    },
    {
        id: 3,
        title: "Diagnóstico inicial",
        subtitle: "5 preguntas de uso actual",
        icon: "quiz",
        duration: "10 min",
        level: "Humano + Simple",
        color: "#7C3AED",
        stepType: "diagnostic",
        description:
            "Responde cinco preguntas cortas sobre cómo usas la IA hoy para identificar tu punto de partida.",
        topics: [
            "5 preguntas de opción múltiple",
            "Lenguaje cotidiano",
            "Una pregunta por pantalla",
            "Retroalimentación amable",
        ],
    },
    {
        id: 4,
        title: "Fundamentos sobre IA",
        subtitle: "Lectura breve y con voz",
        icon: "menu-book",
        duration: "12 min",
        level: "Ligero + Humano",
        color: "#10B981",
        stepType: "reading",
        description:
            "Lee una explicación breve sobre qué es la IA, qué no es y cómo usarla con criterio ético.",
        topics: [
            "3 a 5 párrafos cortos",
            "Ejemplos locales de Cauca",
            "Opción de escuchar el texto",
            "Lenguaje claro y sin tecnicismos",
        ],
    },
    {
        id: 5,
        title: "Mejora un prompt",
        subtitle: "Práctica con retroalimentación",
        icon: "edit-note",
        duration: "15 min",
        level: "Simple + Humano",
        color: "#F59E0B",
        stepType: "practice",
        description:
            "Toma un prompt mal hecho y mejóralo usando Rol + Tarea + Contexto + Formato.",
        topics: [
            "Prompt original no editable",
            "Cuadro para escribir tu mejora",
            "Botón de verificación",
            "Sugerencias alentadoras",
        ],
    },
    {
        id: 6,
        title: "Insignia y certificado",
        subtitle: "Cierre del módulo ODS 4",
        icon: "verified",
        duration: "10 min",
        level: "ODS 4",
        color: "#14B8A6",
        stepType: "certificate",
        description:
            "Completa el módulo y genera una insignia digital con PDF y código QR para certificar el aprendizaje.",
        topics: [
            "Insignia digital",
            "Certificado PDF",
            "Código QR verificable",
            "Enfoque en Educación de Calidad",
        ],
    },
];